# Generated by Django 4.0.5 on 2022-06-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_created_at_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
