# Generated by Django 4.0.5 on 2022-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='./static/images/default-website-landing-page.png', upload_to='profile/'),
        ),
    ]
