# Generated by Django 4.0.5 on 2022-06-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_bio_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/profile/unknown-person_yaj2zi', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='landing_page',
            field=models.ImageField(default='media/photos/default-project_n5fpfv', upload_to='photos/'),
        ),
    ]
